### ISSUE TITLE
MQTT  need help

### ISSUE THREAD

**Issue by Ravikiran28** [jvanderl/flogo-components#1]
Hi Jan,

I am new to Tibco Flogo . Trying to learn and implement more interested  towards Web UI side.

Currently , I am trying 2 things.

1.From MQTTLens I am  trying to publish sample message and I want to receive the same message at 
   Tibco Flogo which I am using MQTTReciever  and log. Please find attached screenshot 1 & and 2

2. I am  trying to build sample flow in web UI.
    Publish message using MQTTSend activity
   and Receive the Message using MQTTReciever.

Can you please help me on both the scenarios since I am struggling with it from quit long time.

but no success.
![task1-1](https
![task1-1](https://user-images.githubusercontent.com/29427328/28373684-88404c7a-6cc0-11e7-84f5-67ed9c0c025f.png)
://user-images.githubusercontent.com/29427328/28373596-64500e72-6cc0-11e7-81a6-e5c4d5366c81.png)
![task1-2](https://user-images.githubusercontent.com/29427328/28373597-645427be-6cc0-11e7-8dde-90cdac392727.png)
![task1-3](https://user-images.githubusercontent.com/29427328/28373598-645febbc-6cc0-11e7-9a94-46eb571c883b.png)

This is for second Task 

![image](https://user-images.githubusercontent.com/29427328/28373803-dd85d6a0-6cc0-11e7-8cd2-b88e43ff2f21.png)

Thanks in Advance!

Regards,
Ravikiran

**Comment by jvanderl** [comment]
I Just reworked the MQTT activity. The trigger still needs work. Even though it's a long time since you tried. Let me know if you still need more info and I'm happy to help.
