### ISSUE TITLE
Compiltion error

### ISSUE THREAD

**Issue by fred-modulist** [jvanderl/flogo-components#2]
Hi @jvanderl,

Thank you so much for your contribution here. I am trying your sample to read from an SCD device.

I was wondering if you have tried your module on the latest flogo yet? I am getting some compilation errors.

warn: [18:58:32.295] Engine does not exist. Creating...
info: [18:58:32.296] Exec command: flogo create -f /flogo-web/local/engines/exported-app-build.json app-build in /flogo-web/local/engines
info: [18:58:32.299] run command: flogo create -f /flogo-web/local/engines/exported-app-build.json app-build
engine:create: 10648.679ms
info: [18:58:42.945] undefined {"durationMs":10657}
info: [18:58:42.946] [log] Build flogo: "flogo build -o,-e" compileOpts:
info: [18:58:42.950] run command: flogo build -o -e
warn: [18:58:43.156] command exited with code 1: flogo build -o -e
error: [18:58:43.156] Error building project: # github.com/jvanderl/go-gatt
/go/pkg/mod/github.com/jvanderl/go-gatt@v0.0.0-20170531215546-1e18d04300aa/central.go:118:11: undefined: central

Kind regards,

**Comment by jvanderl** [comment]
Hi,

I've just reworked this component to adhere to the latest standards in Flogo. Should work fine now.
